### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by M3II0** [Fierioziy/ParticleNativeAPI#10]
Will this source support 1.20.2?

**Comment by Fierioziy** [comment]
Hi, probably yes.  
If something is not working, I'll check it in this week

**Comment by M3II0** [comment]
sk.m3ii0.magicalwands.code.particles.api.utils.ParticleException: Failed to load particle library.
Is it fixable?

**Comment by Fierioziy** [comment]
Probably yes, currently checking what has changed, I'll try to give answer today or tomorrow

**Comment by M3II0** [comment]
Thanks for your time. I need this to update my premium resource to 1.20.2. And I'm too lazy to create packet based particles. Your resource is very useful.

**Comment by Fierioziy** [comment]
I've confirmed that it will be small change; only NMS method for sending packets changed location a little bit.  
Adjusting to this only change seems like everything is working fine now.

Also 2 new particles came in around 1.20.1.

I'll check if everything is working fine and fixed version should be present soon

**Comment by Fierioziy** [comment]
Fixed in version 4.1.0 with added 2 new particles

**Comment by M3II0** [comment]
Thanks
