### ISSUE TITLE
Request 1.20.5 support

### ISSUE THREAD

**Issue by eiqq** [Fierioziy/ParticleNativeAPI#12]
<img width="987" alt="log" src="https://github.com/Fierioziy/ParticleNativeAPI/assets/79748558/41129f52-a797-4f47-a92e-187ba7d908a2">

[log.txt](https://github.com/Fierioziy/ParticleNativeAPI/files/15147290/log.txt)

**Comment by eiqq** [comment]
OMG, 1.20.6 has released

**Comment by Fierioziy** [comment]
Thanks for info, I'll check soon what has changed

**Comment by eiqq** [comment]
> Thanks for info, I'll check soon what has changed

Thanks for your support

**Comment by Fierioziy** [comment]
Current status is that code and unit tests seems adjusted fine and works in MC 1.20.6

Still need to finalize unit tests + test everything on all supported versions and after that new version will be published
